### ISSUE TITLE
Capitol letters not recognized for 144.1 Departmental radio.

### ISSUE THREAD

**Issue by francinum** [GunHog/MAGNI-Tcomms#1]

**Comment by GunHog** [comment]
Details? I need something more descriptive. Are you using a word recognized by the AI word converter? If so, the entire sentence must be in caps.

**Comment by francinum** [comment]
No, the department radio sender for the AI on 144.1.
Sending: [e engineering] would send [engineering] to engineering, but instead sends [E engineering] to Common.

**Comment by GunHog** [comment]
Sorry for being so slow. That behavior is intended so it does not eat one-letter words such as "A" or "I". The only other alternative would be to force a symbol beforehand, such as "-a, -e, -c" and such.

**Comment by GunHog** [comment]
I did not notice that the the speech change completely broke the script. I am sorry for not giving this higher priority. It is fixed now though!
