### ISSUE TITLE
This project is now discontinued.

### ISSUE THREAD

**Issue by GunHog** [GunHog/MAGNI-Tcomms#15]
To all who used to use this script, I must apologize, but I am no longer maintaining this project, as NTSL has been removed from /tg/. You can thank MrPerson and Aranclanos for that.

There will be no further updates to this script, but I will leave this repo up for a while in case you play on a better codebase in which this script still works. I thank you all for using it, and I am happy that you enjoyed the work I put into its many features and uses - the best script on the net for NTSL.

I wish all of you well,
*Gun Hog*

EDIT: Keeping it running for now, to support the Hippies, who still believe in fun!

**Comment by Memendia** [comment]
*There will be no further updates to this script*
Lies!

**Comment by GunHog** [comment]
Well, Nexie is pretty much keeping it alive, thanks to the Hippies. So I will leave it up for them!

**Comment by Memendia** [comment]
NTSL removed from Hippie.... RIP any future this script had...

**Comment by GunHog** [comment]
Pathetic.

**Comment by GunHog** [comment]
Closing this because Hippies are fun again
