### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [GunHog/MAGNI-Tcomms#18]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by GunHog** [comment]
It is not copyrighted or anything like that. Under what law are you prohibited from using code I posted in a public space? Is it not "open source" by virtue of the source code being public?

**Comment by GunHog** [comment]
So I finally got around to this. License is now MIT.
