### ISSUE TITLE
Ai has no emotion on radio

### ISSUE THREAD

**Issue by palpatine213** [GunHog/MAGNI-Tcomms#5]
When attempting to declare or query, the AI will still state, and any punctuation is dropped off of the sentence.

**Comment by GunHog** [comment]
Provide more details please? Btw, now that https://github.com/tgstation/-tg-station/pull/8410 is merged, I am going to work with the NTSL code for the game itself and enable support for scripts to modify that.

**Comment by palpatine213** [comment]
Typing  ;say "Who's there?"
will say on the radio: AI states "Who's there"
rahter than: AI queries "Who's there?"
any punctuation seems to be dropped such as a period, question mark, or exclamation point, leaving it to just parse the words you say without any punctuation.

**Comment by palpatine213** [comment]
I figured it out it drops the last punctuation off of the sentence. if you use two exclamation points, it works fine

**Comment by GunHog** [comment]
Strange. Could be a parsing error? I will look into it.

**Comment by GunHog** [comment]
Direct your attention to this: https://github.com/tgstation/-tg-station/pull/8488 once this baby is pulled, I am going to integrate saymods and spans into NTSL itself, so anyone can change them how they wish via scripts. I will of course implement a custom set in mine.

**Comment by palpatine213** [comment]
Ok. I Finally narrowed the cause down! If you disable the word converter, then it removes the punctuation. turning it back on restores it.

**Comment by GunHog** [comment]
Phew, I took FIVE-EVAR to get around to this, sorry. Game code gets me caught up sometimes. This is fixed in Version 1.71.
