### ISSUE TITLE
AI Track is broken by the script if job is in the name.

### ISSUE THREAD

**Issue by francinum** [GunHog/MAGNI-Tcomms#7]

**Comment by GunHog** [comment]
This is a code issue, broken by Aranclanos when he changed how AI hrefs work. Using the -jobmode command will resolve this, but will look absolutely awful. I will consider a toggle to disable it entirely.

**Comment by GunHog** [comment]
I have a small workaround for now, I can add the job to the saymods in the signal, this will somewhat be better than adding it to message content. This is all I can do for now.

**Comment by francinum** [comment]
That'll do.
